### ISSUE TITLE
Blank window with Nvidia proprietary drivers

### ISSUE THREAD

**Issue by nicoulaj** [aperezdc/revolt#29]
I tried to install and run revolt, the window stays blank and the console shows:
```
$ flatpak run org.perezdecastro.Revolt
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:15): Gdk-ERROR **: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 177 error_code 2 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

```

System: up to date Arch Linux (GNOME 3.22)

**Comment by clopez** [comment]
Are you using graphics drivers not based on mesa (like the proprietary ones from NVIDIA) ?
Then that explains what is happening, because the flatpak runtime only has the mesa opengl drivers installed. Here is the bug report on the flatpak side: https://github.com/flatpak/flatpak/issues/138

In the meanwhile you can tell WebKitGTK+ to disable OpenGL support by exporting the environment variable [WEBKIT_DISABLE_COMPOSITING_MODE](https://trac.webkit.org/wiki/EnvironmentVariables), for example by runnnig :

`WEBKIT_DISABLE_COMPOSITING_MODE=1 flatpak run org.perezdecastro.Revolt`

**Comment by nicoulaj** [comment]
Yes, running NVIDIA proprietary driver.
The workaround works.

**Comment by aperezdc** [comment]
Maybe it would be just fine to always set `WEBKIT_DISABLE_COMPOSITING_MODE=1` in the environment. As far as my testing goes, Riot seems to work just fine with it, without any loss in funcionality. We could do that while there is not an easy way for people to get proprietary OpenGL drivers to work within the Flatpak sandbox. Thoughts?

**Comment by clopez** [comment]
I would not add it unconditionally. The web inspector is currently broken without AC: https://bugs.webkit.org/show_bug.cgi?id=165237

What can be interesting is adding setting that allows the user to turn it off and on.

And it can be also very interesting that when the webprocess crashes (it will happen when AC is not working) an error button to reload the webview in "safe mode (disabling AC)" is added.  (related to #15)

**Comment by aperezdc** [comment]
@clopez Thanks for all the info, that's very useful. Because disabling AC comes with its own quirks (e.g. the inspector issue) and it is something that should eventually get fixed in WebKitGTK+, I think we can:

* Have a setting for disabling AC, but without exposing it in the user interface. In the documentation (the `README` for now) we can document how to toggle it using `gsettings` from the command line.
* Handling the web process crashes with an extra “reload in safe mode” option, which disables AC only for the current execution of the program (without saving the setting).

**Comment by aperezdc** [comment]
I have been mulling about this a bit longer. Having the user need to toggle a low-level setting like enabling/disabling AC would be really bad UX, and better avoided — users should't need to know what Accelerated Compositing is. A better approach would be:

- Given that Riot itself works without AC, we would have it disabled by default.
- If an user enables the “Developer Tools” option in the settings, we enable AC to ensure that the inspector works.

Developers are more likely to tolerate issues (and actually help debugging them), but we shouldn't push regular users to play around with obscure settings.

**Comment by aperezdc** [comment]
There's a [WebKitGTK+ bug](https://bugs.webkit.org/show_bug.cgi?id=165237) for the inspector and AC mode, too.

**Comment by clopez** [comment]
Maybe another idea is to fix that webkitgtk+ bug and disable AC always? I don't think AC adds something useful to Riot other than more memory usage and brokenness due to graphics drivers.

**Comment by aperezdc** [comment]
Well, certainly fixing things in WebKitGTK+ is even better, as it can benefit other applications using it as well :wink:

**Comment by indolering** [comment]
[WebGL black/whitelisting is common in the browser world](https://www.khronos.org/webgl/wiki/BlacklistsAndWhitelists) and I would assume that WebKitGTK would have a similar ruleset for WebGL, but my Google-foo is failing me!  Has anyone looked upstream?

How is performance with it disabled?

**Comment by clopez** [comment]
@indolering commented 6 hours ago
> 
> WebGL black/whitelisting is common in the browser world and I would assume that WebKitGTK would have a similar ruleset for WebGL, but my Google-foo is failing me! Has anyone looked upstream?
> 
The issue is not with WebGL, but with accelerated compositing rendering (Using OpenGL for drawing).
We don't have a blacklist for GPU drivers on WebKitGTK+, but we are considering implementing one.

> How is performance with it disabled?

Unless the website has lot of animations you are not going to notice any difference.
For Riot the performance is the same with AC disabled or enabled.
And with AC disabled it uses less memory and is more reliable (specially if your OpenGL drivers are not very reliable).

**Comment by indolering** [comment]
> The issue is not with WebGL, but with accelerated compositing rendering (Using OpenGL for drawing).

The end result remains the same and I would assume they have similar schemes for layout rendering.

> We don't have a blacklist for GPU drivers on WebKitGTK+, 

I'm out of my depth here, but isn't this a security issue as well?

> but we are considering implementing one.

I can't imagine why you _wouldn't_ follow the upstream browser vendor's blacklisting scheme here as well.

> Unless the website has lot of animations you are not going to notice any difference.

Or you are doing a lot of scrolling, the UI should be less janky.  You could implement a scheme that dedicates fewer resources to apps that don't have input focus....  

Either way, I think there is consensus to disable now and push a ticket upstream for driver blacklisting based on browser vendors + telemetry of some sort?

**Comment by clopez** [comment]
@indolering commented 2 hours ago
> We don't have a blacklist for GPU drivers on WebKitGTK+,
> 
> I'm out of my depth here, but isn't this a security issue as well?

I don't see how that could be a security issue. Can you elaborate on how this can be hypothetically exploited?

> Either way, I think there is consensus to disable now and push a ticket upstream for driver blacklisting  based on browser vendors + telemetry of some sort?

The final call depends on @aperezdc but for my part I'm all in for unconditionally disabling WebKitGTK+ AC mode from Revolt (by setting that env var until an API is provided for that)

Also, there is already a patch attached in the WebKit bugzilla fixing the issue with the web inspector and AC mode disabled. I think such patch will be ported to the next stable release 2.14.4 that should happen soon.
That may be also a good moment to make this change in Revolt.

**Comment by aperezdc** [comment]
I have also been following the WebKitGTK+ bug which prevents the inspector from working on non-AC mode. Given that AC is not strictly required for Riot (and Revolt), let's disable AC (using the environment variable) once there is at least stable release of WebKitGTK+ where the inspector works without AC — I would have to break the AC as I am using it myself to figure out how we can inject some JS hook into Riot for a few things (for example, see #39 or #38).

**Comment by indolering** [comment]
> I don't see how that could be a security issue. Can you elaborate on how this can be hypothetically exploited?

Like I said, I'm out of my depth here but I know there has been a lot of controversy over GPU acceleration in browsers.  AFAIK, it's generally considered a dangerous thing (it's turned off in paranoid mode in the TBB) and I don't think it's appropriate for an E2E message app to be taking that risk until someone who knows better gives us the okay.

>  let's disable AC (using the environment variable) once there is at least stable release of WebKitGTK+ where the inspector works without AC

Since there doesn't appear to be a blacklist upsteam, what if we started by creating one?  After reading some tickets, Chromium and Firefox appear to be using the same blacklist (part of an effort to get driver vendors off-their-ass) and [Chromium has there's on Git](https://cs.chromium.org/chromium/src/gpu/config/).  This could eventually get pushed upstream if it works....

**Comment by aperezdc** [comment]
@indolering: IMHO whether WebKitGTK+ would use or not a GPU blacklist is something which would be better to discuss in an issue at [bugs.webkit.org](https://bugs.webkit.org). Doing a quick search I have not found an issue for that, so you may want to go ahead and create a new bug for that there :wink:

**Comment by aperezdc** [comment]
FWIW, WebKitGTK+ will have new API to configure AC (see upstream [bug #167509](https://bugs.webkit.org/show_bug.cgi?id=167509), so let's use that instead the environment variable.
