### ISSUE TITLE
E2E issues due to missing WebCrypto support in WebKitGTK+

### ISSUE THREAD

**Issue by jomat** [aperezdc/revolt#53]
In order to switch from riot-web to revolt importing previously exported keys fails with: `undefined is not an object (evaluating '_.importKey')`

**Comment by aperezdc** [comment]
As with #34, this is not working due to missing WebCrypto support in WebKitGTK+ — once it implements the needed APIs, things will just work. The goods news is that [there has been a bunch of upstream activity](https://bugs.webkit.org/show_bug.cgi?id=133122) to get WebCrypto working.

In the meanwhile, sorry about the inconvenience :disappointed:

**Comment by aperezdc** [comment]
Let's use this issue for all bugs related to WebKitGTK+ missing a WebCrypto implementation.

**Comment by aperezdc** [comment]
[WebKitGTK+ version 2.17.90](https://webkitgtk.org/2017/08/09/webkitgtk2.17.90-released.html) (which is a release candidate for 2.18.0) has been announced today, and it will have WebCrypto support built in by default.

**Comment by aperezdc** [comment]
I have pushed a new version to the Flatpak repository (`0ec092f400dd`) which uses the GNOME 3.26 runtime, which in turn includes WebKitGTK+ 2.18 with WebCrypto support. The part of key export which involves WebCrypto seems to work (and there is no console errors) but then #81 kicks in.

**Comment by aperezdc** [comment]
This has been working fine with the GNOME 3.26 runtime, so let's close it for now. Please reopen if the issue manifests itself again.
