### ISSUE TITLE
Why do revolt's notifications have "critical" urgency?

### ISSUE THREAD

**Issue by jplatte** [aperezdc/revolt#67]
I don't really see why IM notifications should stay until you manually dismiss them, and I haven't seen any other IM applications send their notifications as critical.

**Comment by aperezdc** [comment]
The priority used for notifications in Revolt is [G_NOTIFICATION_PRIORITY_HIGH](https://developer.gnome.org/gio/stable/GNotification.html#GNotificationPriority), which is recommended...

> for events that require more attention, usually because responses are time-sensitive (for example chat and SMS messages or alarms)

...because Revolt wraps Riot, which _is_ a chat application. It is trying to follow the GNOME interface guidelines. Also, notice that when focusing Revolt existing notifications will be automatically dismissed, so you may as well just leave them around as a reminder that you have messages to read, and when switching to Revolt they will be gone.

**Comment by jplatte** [comment]
That's interesting... GNotification knows four "priorities" (low, normal, high, critical), while libnotify only knows [three "urgencies"](https://developer.gnome.org/libnotify/unstable/NotifyNotification.html#NotifyUrgency) (low, normal, critical).

The reason I actually opened this issue isn't because I'm bothered by having to manually dismissing notifications actually (although that could still be a problem, time will tell) but because my current configuration for the libnotify frontend I use ([dunst](https://dunst-project.org/)), as well as its default configuration, display notifications with critical urgency in a box with red background, which is quite distracting.

I guess I should try whether gnome's own IM program, empathy, also sends "critical" notifications. I'm pretty sure Pidgin doesn't, FWIW.

**Comment by jaragunde** [comment]
FWIW, in messaging applications for other platforms (e.g. WhatsApp, even Riot on Android), notifications stay until you manually dismiss them or you open the messaging app. Revolt also behaves like that, and if notifications don't disappear when you focus the Revolt window, that's a bug!

**Comment by aperezdc** [comment]
@jplatte I wonder whether GIO (GNotification) maybe should map `G_NOTIFICATION_PRIORITY_HIGH` to `NOTIFY_URGENCY_NORMAL` instead, when the notification daemon supports only the three levels used e.g. in `libnotify`. Dunno if that's even possible...

I'll try to ask the GLib people in IRC about this.

**Comment by aperezdc** [comment]
Talking with `fmuellner` in `#gtk+` GIMPNet ([link](https://matrix.to/#/!MESkLeHPSisUiZFvNN:matrix.org/$1499799616460123Hchnk:matrix.org)), it turns out that:

- The [GLib code](https://git.gnome.org//browse/glib/tree/gio/gfdonotificationbackend.c#n205) does indeed map `G_NOTIFICATION_PRIORITY_HIGH` to `NOTIFY_URGENCY_CRITICAL`.
- It could be that it made sense to map it to `NOTIFY_URGENCY_NORMAL` instead.

I will be sending a patch to GLib to use `NOTIFY_URGENCY_NORMAL` instead.

**Comment by aperezdc** [comment]
The patch for GLib is now attached [to the corresponding bug report](https://bugzilla.gnome.org/show_bug.cgi?id=784815). Let's wait and see how that goes.

**Comment by clopez** [comment]
FTR ... not setting notification high is done if XFCE environment is detected, see commit 0d2e955372aa7ffba64a45d66c068fa33253bc77 

maybe an idea is to do this for other DEs also

**Comment by aperezdc** [comment]
@clopez: That fix seemed pretty XFCE-specific, so I think it should _not_ be carried over to other DEs. GLib has been already fixed to map the priority to `NOTIFY_URGENCY_NORMAL` as discussed, so I expect that all other DEs which use the original `notification-daemon` (or which properly implement the notification spec) will work just fine.

Of course, if some particular DE needs a specific fix like XFCE (which seems won't fix their notification daemon implementation), we should open a new issue and discuss these kind of fixes in a case-by-case basis.

**Comment by aperezdc** [comment]
@jplatte: The patch for GLib should be part of the GNOME 3.26 release. Could you run `flatpak update` to get the newer Revolt version (`0ec092f400dd`) and confirm whether notifications behave better now? (Or, alternatively, having GLib 2.54 installed in the system if you don't use Flatpak.)

**Comment by jplatte** [comment]
@aperezdc Arch linux doesn't seem to be on GNOME 3.26 yet. But I'll try it as soon as the updates roll in :)

**Comment by aperezdc** [comment]
@jplatte: GNOME 3.26.1 has been in Arch Linux for a bit. Could you confirm that this is now fixed for you? Hopefully we can close this issue :slightly_smiling_face:

**Comment by jplatte** [comment]
@aperezdc Yeah, I no longer get critical urgency notifications from Revolt. Thanks! :)

**Comment by aperezdc** [comment]
@jplatte: Awesome, thanks for confirming and closing the issue! :+1:
