### ISSUE TITLE
Option to disable CSD?

### ISSUE THREAD

**Issue by hjri** [aperezdc/revolt#85]
It looks very ugly in DEs with SSDs or in environments with no decorations at all.

**Comment by aperezdc** [comment]
Hi there! There is already an option to disable header bars (which use client side decorations). You can toggle this option using the following command:

```sh
gsettings set org.perezdecastro.Revolt:/org/perezdecastro/Revolt/ \
    use-header-bar false
```

If you want to re-enable header bars, just replace `false` with `true`. Note that you will need to restart the application for the change to take effect.

Let me know if this solution works for you. Cheers!

**Comment by hjri** [comment]
it works, however "preferences" window still has CSD. Also I think there should be GUI for this, like a toggle in "preferences" window, because it's not obvious, especially to non-gnome user.

**Comment by aperezdc** [comment]
@hjri: The non-CSD mode is not officially supported because it's not well tested — as you have found already with the preferences window not respecting the setting. That's the reason why there isn't a toggle in the preferences window.

I'll close this because the setting works as expected, and let's track the bug with the preferences window in issue #88.
